server:
  port: 8080

mysql:
  driver-class-name: software.aws.rds.jdbc.mysql.Driver
  username: root
  password:
  write:
    name: write
    url: jdbc:mysql:aws://{writer_cluster_endpoint}/test
  read:
    name: read
    url: jdbc:mysql:aws://{readonly_cluster_endpoint}/test